export const themeColor = {
  primary: '#185952',
  secondary: '#2A9D8F',
  btnColor: '#2A9D8F',
  screenColor: '#EEF0F3',
  statusbarColor: '#EEF0F3',
  transparent: 'transparent',
  textSecondary: '#303030',
  cancelColor: '#FFD6D6',
  rescheduleColor: '#D6E8FF',
  remindColor: '#FFF9CC',
};
export const theme = {
  light: {
    primary: '#185952',
    secondary: '#2A9D8F',
    tertiary: '#2A9D8F20',
    btnColor: '#2A9D8F',
    screenColor: '#EEF0F3',
    statusbarColor: '#EEF0F3',
    transparent: 'transparent',
    textSecondary: '#303030',
    cancelColor: '#FFD6D6',
    rescheduleColor: '#D6E8FF',
    remindColor: '#FFF9CC',
  },
  dark: {
    primary: '#212121',
    secondary: '#1E1E1E',
    tertiary: '#D8DFE9',
    btnColor: '#1E1E1E',
    screenColor: '#EEF0F3',
    statusbarColor: '#121212',
    transparent: 'transparent',
    textSecondary: '#000000',
    cancelColor: '#FFD6D6',
    rescheduleColor: '#D6E8FF',
    remindColor: '#FFF9CC',
  },
  blue: {
    primary: '#003366',
    secondary: '#336699',
    tertiary: '#33669920',
    btnColor: '#336699',
    screenColor: '#EEF0F3',
    statusbarColor: '#CCFFFF',
    transparent: 'transparent',
    textSecondary: '#003366',
    cancelColor: '#FFD6D6',
    rescheduleColor: '#D6E8FF',
    remindColor: '#FFF9CC',
  },
  Licorice: {
    primary: '#270320',
    secondary: '#59044A',
    tertiary: '#FFF8FE',
    screenColor: '#EEF0F3',
    cancelColor: '#FFD6D6',
    rescheduleColor: '#D6E8FF',
    remindColor: '#FFF9CC',
  },
};
